app:
  name: quarkus-todo-app
  namespace: iocanel
  virtualMachineName: quarkus-dev
  virtualMachineNamespace: demo
  cluster:    #

build:
  native: false

git:
  branch: main
  repo: github.com
  org: iocanel
  name: quarkus-todo-app

image:
  url: quay.io/ikanello/quarkus-todo-app
  registry:  # NOT USED
  organization:  # NOT USED
  name:  # NOT USED